# Generated by Django 5.1.1 on 2026-04-11 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock_umbral_amarillo',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_umbral_rojo',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_unidades',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
