# Generated by Django 5.1.1 on 2026-04-13 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_stock_umbral_amarillo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='precio_mayor',
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_compra_caja',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_compra_unidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
