# Generated by Django 5.1.1 on 2026-04-13 03:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_pedido_fecha_vendido_alter_pedido_estado'),
        ('productos', '0003_remove_producto_precio_mayor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('vendido', 'Vendido'), ('no_entregado', 'No entregado'), ('anulado', 'Anulado')], default='pendiente', max_length=20),
        ),
        migrations.CreateModel(
            name='DevolucionPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('parcial', 'Entrega parcial'), ('no_entregado', 'No entregado')], max_length=20)),
                ('motivo_general', models.TextField(blank=True, null=True)),
                ('estado_reposicion', models.CharField(choices=[('pendiente', 'Pendiente'), ('parcial', 'Parcial'), ('repuesto', 'Repuesto')], default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoluciones', to='pedidos.pedido')),
                ('repartidor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='DevolucionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_devuelta', models.PositiveIntegerField(default=0)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('repuesto', models.BooleanField(default=False)),
                ('fecha_reposicion', models.DateTimeField(blank=True, null=True)),
                ('detalle_pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devoluciones', to='pedidos.detallepedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.producto')),
                ('repuesto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devoluciones_repuestas', to=settings.AUTH_USER_MODEL)),
                ('devolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pedidos.devolucionpedido')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
