# Generated by Django 5.1.1 on 2026-04-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_pedido_stock_descontado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='fecha_entrega_estimada',
            field=models.DateField(blank=True, null=True),
        ),
    ]
