# Generated by Django 5.1.1 on 2026-07-18 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_pedido_fecha_entrega_estimada'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='precio_ajustado',
            field=models.BooleanField(default=False),
        ),
    ]
