# Generated by Django 5.1.1 on 2026-04-13 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_foto_tienda'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
